name: Add a contributor
description: Add yourself (or someone else) as a contributor
title: "Add <username> as a contributor"
labels: triage
body:
  - type: markdown
    attributes:
      value: >
        Thank you for contributing!
        Check <https://allcontributors.org/docs/en/emoji-key> for valid contribution types.
        
        Please remember to put your username in the issue title!
  - type: dropdown
    id: types
    attributes:
      label: What contribution types do you want to be recognised for?
      multiple: true
      options:
        - audio
        - a11y
        - bug
        - blog
        - business
        - code
        - content
        - data
        - doc
        - design
        - example
        - eventOrganizing
        - financial
        - fundingFinding
        - ideas
        - infra
        - maintenance
        - mentoring
        - platform
        - plugin
        - projectManagement
        - promotion
        - question
        - research
        - review
        - security
        - tool
        - translation
        - test
        - tutorial
        - talk
        - userTesting
        - video
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Links to your contirbutions (if applicable).
    validations:
      required: false
      
